version: '3.2'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
